version: '3.3'
services:
  api:
    build: .
    ports:
      - "5000:5000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: cloud
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: cloudfun
    ports:
      - "3306:3306"