version: '3.3'
services:
  # web:
  #   image: nginx:1.16.0-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx:/etc/nginx/conf.d
  # uwsgi:
  #   build: .
  #   environment:
  #     DB_HOST: db
  #     DB_NAME: cloudfun
  #     DB_USER: cloud
  #     DB_PASS: fun
  python:
    image: python:3.7.8
    container_name: python3.7.8
    command: pip install -r requirements.txt
    volumes:
      - ./:/app_python
    tty: true
    depends_on: 
      - db
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: cloudfun
      MYSQL_USER: cloudfun
      MYSQL_PASSWORD: cloudfun
      MYSQL_ROOT_PASSWORD: cloudfun
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - mysql_data_volume:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
volumes: 
  mysql_data_volume:
